### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by mictadlo** [tanghaibao/allhic#3]
Hi,
I used the following command `allhic pipeline all.hic.sorted.dedup.bam $1 $2 --RE $3 --resume` but got the following error:

```
Contig #1510 (QM4NbP_1511) has 0.0x the average number of Hi-C links -> MARKED REPETITIVE
Contig #1511 (QM4NbP_1512) has 0.0x the average number of Hi-C links -> MARKED REPETITIVE
19:48:31 skipRepeats | NOTICE  Marked 1512 contigs (avg len 1835061) as repetitive (MaxLinkDensity = 0)
19:48:31 Cluster | NOTICE  There are no informative contigs for clustering. Contigs are either SHORT or REPETITVE.
19:48:31 Cluster | NOTICE  Clustering starts with 1512 (0 informative) contigs with target of 19 clusters
19:48:31 Cluster | NOTICE  No more merges to do since the queue is empty
19:48:31 printClusters | NOTICE  Write 0 partitions to `all.hic.sorted.dedup.clusters.txt`
19:48:31 Run | NOTICE  Success
19:48:31 banner | NOTICE  *********************************
19:48:31 banner | NOTICE  * Build started (AGP and FASTA) *
19:48:31 banner | NOTICE  *********************************
panic: runtime error: index out of range

goroutine 1 [running]:
main.main.func8(0xc00011edc0, 0xc000088f00, 0xc00011edc0)
        /Users/bao/code/allhic/cmd/allhic.go:388 +0xa65
github.com/urfave/cli.HandleAction(0x90f200, 0x9da360, 0xc00011edc0, 0x0, 0xc000088f00)
        /Users/bao/go/src/github.com/urfave/cli/app.go:501 +0xc8
github.com/urfave/cli.Command.Run(0x9b8160, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x9cca44, 0x37, 0x9d03e0, ...)
        /Users/bao/go/src/github.com/urfave/cli/command.go:165 +0x459
github.com/urfave/cli.(*App).Run(0xc000162000, 0xc00008c000, 0x8, 0x8, 0x0, 0x0)
        /Users/bao/go/src/github.com/urfave/cli/app.go:259 +0x6bb
main.main()
        /Users/bao/code/allhic/cmd/allhic.go:400 +0xb31
```
What did I miss?

Thank you in advance,

Michal

**Comment by tangerzhang** [comment]
The command line "allhic pipeline" is not supported currently. Please use the command lines listed in this link (https://github.com/tangerzhang/ALLHiC/wiki).

**Comment by mictadlo** [comment]
Thank you.
